### ISSUE TITLE
Can you pl share the config.env details?

### ISSUE THREAD

**Issue by rajasekhar-gundala** [peakwinter/stacks#1]
Hi, Thanks for the docker-compose files. I am trying mail server and i didn't locate the config.env file. Can you pl share the details?

Thanks in advance.

**Comment by peakwinter** [comment]
Hi there,

I just updated the repo with these details. :)

You can get more details about the possible parameters for the file here: https://github.com/tomav/docker-mailserver

Good luck!

**Comment by rajasekhar-gundala** [comment]
Thanks for the update. I have successfully deployed the mail stack. How can i create email accounts?
