### ISSUE TITLE
How can i create email accounts?

### ISSUE THREAD

**Issue by rajasekhar-gundala** [peakwinter/stacks#2]
Thanks for the mail server stack. I have successfully deployed the stack. How can i create email accounts? Also how can i use the rainloop web client for the new email accounts?

Thanks for the support.

**Comment by peakwinter** [comment]
Hi,

You can get information regarding the management of your mail server at the container's project wiki, https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts

For rainloop, you can simply login with your mail account's email address and password.
